alerts:
    - rule: DEPLOYMENT_FAILED
    - rule: DOMAIN_FAILED
envs:
    - key: APP_ENV
      scope: RUN_AND_BUILD_TIME
      value: prod
features:
    - buildpack-stack=ubuntu-22
ingress:
    rules:
        - component:
              name: thebreathingnook
          match:
              authority:
                  exact: ""
              path:
                  prefix: /
name: thebreathingnook
region: sfo
services:
    - dockerfile_path: Dockerfile
      github:
          branch: main
          deploy_on_push: true
          repo: deluxetom/thebreathingnook
      http_port: 9001
      instance_count: 1
      instance_size_slug: apps-s-1vcpu-1gb
      name: thebreathingnook
      source_dir: /
