name: Build Docker Image

on:
    push:
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    REGISTRY_IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
    build-and-push-amd64:
        runs-on: ubuntu-24.04
        permissions:
            contents: read
            packages: write
        strategy:
            fail-fast: false
            matrix:
                phpversion:
                    - '8.4'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

#            - name: Build and Push Docker Image
#              run: |
#                  docker pull ${{ env.REGISTRY_IMAGE_NAME }}:latest || true
#                  docker build \
#                    --cache-from "${{ env.REGISTRY_IMAGE_NAME }}:latest" \
#                    --target ecs \
#                    -f Dockerfile \
#                    -t ${{ env.REGISTRY_IMAGE_NAME }}:latest .
#                  docker push ${{ env.REGISTRY_IMAGE_NAME }}:latest

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v6.5.0
              with:
                  context: .
                  push: true
                  target: ecs
                  tags: ${{ env.REGISTRY_IMAGE_NAME }}:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Deploy the app
              uses: digitalocean/app_action/deploy@v2
              env:
                  SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
