name: Build Docker Image

on:
    push:
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    REGISTRY_IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
    build-and-push-amd64:
        runs-on: ubuntu-24.04
        permissions:
            contents: read
            packages: write
        strategy:
            fail-fast: false
            matrix:
                phpversion:
                    - '8.4'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push Docker Image
              run: |
                  docker pull ${{ env.REGISTRY_IMAGE_NAME }}:latest || true
                  docker build \
                    --cache-from "${{ env.REGISTRY_IMAGE_NAME }}:latest" \
                    --target ecs \
                    -f Dockerfile \
                    -t ${{ env.REGISTRY_IMAGE_NAME }}:latest .
                  docker push ${{ env.REGISTRY_IMAGE_NAME }}:latest
